# Generated by Django 4.2.23 on 2025-06-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
